language: node_js
node_js:
- '8'
services:
- postgresql
before_script:
- psql -c 'create database peta;' -U postgres
script: npm run test:ci
addons:
  postgresql: '9.5'
deploy:
  provider: heroku
  api_key:
    secure: mgs6NT1ORn+Z3ObphSdVGiQXumxposXJXSVHAb84xZQN3XT0dBh6wNQAr8hPsg1aMupBw8xPPlvH8TOYyfwlWX2BnYR/GIaRaXvcpG5f/t5qK4f6K6b1ts9TEoohE8l7N0YiCEb/yVNfKmyZXwKgBtg5QTcpAkkZ5pwgPv9KGY2+Abe4LOTlvm2CWkTFfSIkAhKvC7xc4IiVBljlz5ngItVJo0lgYYoybo83CPBttQ1aRHtrC0x/8hi206aGYV5hwhYP39Ppsk5mjEgbgwoMEUccDty188+jud1erhMZqOQVO1EqgNcYQQ5xrJZs3LG0unbZ8uQ9sxpeN3NQ3CLtWUTUaoJoBI/8HXOyTT/O756rMp+S9VHLCcc7R5yMZVVJBhw5FZvybU5v6U9bXqfrCDifnb+UWGdIB2ZUeWTJShm0YCRLHtXnJOtGJB2Na3RlbB++7rG52hQjpVm+iK60w8wdeomY1CxUGoaMnhnWJqwMmmG8pQaxqNJC78IqH874FfHchAEmPQrj1janiG0E4z7XMa/rH3oJjU9xwsqFzCK57hH43eVKkpnCCYqQqD3B35o5FlUtlsKfGCSwlxFaCH+xX9c09uITg0vpAmtXCaf8rxK1vFGO6p3PxLWFWRW2XboLEQfsMwWZGUhMiw+lniCqv+siTLdhQknoUpMVCqU=
