language: node_js
node_js:
- '8'
services:
- postgresql
before_script:
- psql -c 'create database peta;' -U postgres
script: npm run test:ci
addons:
  postgresql: '9.5'
deploy:
  provider: heroku
  api_key:
    secure: ow1+TyP8yWDdTCDeXZJ/lYlxOIUgaU6shspbql0TBF6P7ajo8bi3e4CuK5X3hEO6QaWo9m0fhdIicR/hsMlnXYN2yS2AhcqVEma94ztaCYhstLeuSjV6zXy1PfVcz2NOjRBx/IpqnrMLKKxFbQbWOklAAiqJ3v0BB2FWZP/1Hq1UeK0hIN2H4UbsBsrUD8myfL1DpVtTc9IPwmBTzeEpAh8VLcp3NNO9EyfeZK/Q8AspPSKibiddgpaZt3P7eCwpGRsmTJ7Lzg812Bo85yDr6sFjiWwNTcKpdCZ4nTDYKhi0MAXrRoXe5gYyJ+jYe+N9Bf/35Ug+iNy5yEMw+kMxygO68MoTchnFrfQSZRwvDnKfy7dd6K+avy+VP1bK7NjxWeG0g51jQf8KIK+CGzweR8Oz3GM8S772Abv1e7TDFhDoAEUfKNoi3i7eQD1abdE7g9O42RHHT7ZytrNnApqKjQstmFHdv8BHK3B95aBTjZJtK4h4NrZEunsKcJiXOzFFkisZ3j3MCP90emUEaQTo7I/IU+MISEqyHuQOmdwVOgjKYP1fXeBJSvWEGimOlZn0Hv08yM4znIJ6rs9aqScADXZMvPajQmtM6mLXdBBVeU3xiXPc/3tUPrzsZ4dfmddbLsrgf0Qowyzqvv0zBZ+JWAMlZfbihRSmQWgZeFguFtI=
  app: fathomless-bastion-92074
