language: node_js
node_js:
- '8'
services:
- postgresql
before_script:
- psql -c 'create database peta;' -U postgres
script: npm run test:ci
addons:
  postgresql: '9.5'
deploy:
  provider: heroku
  api_key:
    secure: 3iNkeFU6SMt6E2WmLnjN5Cn0YNt2s7B/U5WgU8XcXAFwIHUBpFTbbEEF+/3NXmwmpgVOLgGOM9gc7Ob7TJeNk9zlgggOE6mYYHzpuOSCz0E1VYF4ZRht5+IguU7XNinZqOtqIvpYIk3tVaK4TzitjT3CQ4NcgUAszFMJfdThnm7Pf4Yd0KQ3opSGmB6e/16qK9ZwukpAxCnxwcroW+VxncmF7V8XKvYJsqpcUpeyd8/WAK1qdCzebtXyyZPsmrHFBsKfgr0+5BAN85/JpGZb4ExNBdNziG+arlG0poQrW9koSres+196rzLynKfWiPgra7TxwQtaAlaHGl5tM1m5tT7OgJDBkvLFYkGQq3jlBsazDY3BPv5lRLosl2EmV9ZDBmeTo8tf8+qgAlp4NTn6m7kNXpb1sl23Quk5PJSo3u8IDCgQiGQAthAOBBahWwJrkldQkF99XxRESFNfGN77F+hwQkw1KGWm+Ylo8XTmWQVw0UWHN0dOvD4/oCWNkszNm3PmSfC0I4Z/qqKsloi7B5nRxBey2WQGuipDvF4apB73GfqM8rmEm2TvmqKf/e7F9oAa++8i3tJJlMRvqhRIwjwJmV4TH1T34cINhtnVNxr2+xWKyrT2XUIaE1ZkbylEJARRz6AUkEQAoHJr5HGw7qt5NTWX/m6PLdN/gsLQdmI=
  app: fathomless-bastion-92074
