version: '2'

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=peta
        ports:
            - "5432:5432"